version: "3"

services:
  namenode:
    image: orozcohsu/hadoop-namenode:1.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9000"
    ports:
      - 50070:50070
      - 14000:14000
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoopbase/hadoop.env

  datanode:
    image: orozcohsu/hadoop-datanode:1.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoopbase/hadoop.env

  resourcemanager:
    image: orozcohsu/hadoop-resourcemanager-multi-tenant:1.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  nodemanager:
    image: orozcohsu/hadoop-nodemanager:1.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  historyserver:
    image: orozcohsu/hadoop-historyserver:1.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env

  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    volumes:
      - /etc/localtime:/etc/localtime:ro

  submit:
    image: orozcohsu/hadoop-capacity-submit:1.0.0-hadoop2.7.4-java8
    container_name: submit
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoopbase/hadoop.env
    volumes:
      - /etc/localtime:/etc/localtime:ro

  driver:
    image: orozcohsu/hadoop-capacity-driver:1.0.0-hadoop2.7.4-java8
    container_name: driver
    volumes:
      - ./data:/data  
      - /etc/localtime:/etc/localtime:ro
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    command: tail -f /dev/null
    env_file:
      - ./hadoopbase/hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
