hadoop_branch := 1.0.0-hadoop2.7.4-java8

build:
	docker build -t orozcohsu/hadoop-capacity-submit:$(hadoop_branch) ./submit
	docker build -t orozcohsu/hadoop-capacity-driver:$(hadoop_branch) ./driver

